.gitignore, README.md, package.json
Rename `site-template.zip` to `aem-site-template-basic-1.0.0.zip`
Manually
=> Update to aem-site-template-builder 0.2.0

theme/.github/workflows/update-theme-config.yml
- update the Github action to send a request that AEM can handle
=> CQ-4308902 - [CreateSite] Secure logic to deploy theme reference

theme/.github/workflows/update-theme-config.yml, theme/package.json
use latest version of aem-site-theme-builder
=> Cq 4308902 theme update

package.json, theme/src/main.scss, theme/src/site/_variables.scss
Introduction of Normalize CSS to the basic template to achieve consistent better look across different browsers.
=> Normalize css

.github/workflows/release.yml, README.md
=> Update Site Theme E2E test repo

theme/package.json
Updated `@adobe/aem-site-theme-builder` dependency from `2.0.2` to `2.0.4`.
=> theme-builder update to 2.0.4 version

theme/.github/workflows/update-theme-config.yml, theme/env_template, theme/package.json
- prefix env vars:
SITE -> AEM_SITE
URL -> AEM_URL
EXPIRATION -> GIT_HASH_EXPIRATION
HASH -> GIT_HASH
=> CQ-4308112 - [SiteTemplate] Namespace the theme env vars

theme/.github/workflows/deploy.yml, theme/README.md, theme/package.json
PR reduces number of available npm scripts in the theme of site template.
Before:
`
"dev",
"dev-watch",
"live",
"proxy",
"prod",
"browsersync"
`
After:
`
"build",
"live"
`
`npm run build` produces production ready (minified) version of code.
`npm run live` watches for code updates, sets up proxy from theme-builder, sets up browser reload
=> CQ-4308305 - Simplfication of npm scripts

package.json
Update of `@adobe/aem-site-template-builder` dependency from `1.0.0` to `2.0.0`.
Removed wrong `normalize.css` dependency.
=> template-builder version 2.0.0

theme/package.json
`theme-builder` dependency update from `4.0.0` to `4.0.1`
=> theme-builder dependency update from 4.0.0 to 4.0.1

package.json
=> update aem-site-template-builder 2.1.2

site/src/main/content/jcr_root/content/experience-fragments/aem-site-template-basic/.content.xml
Add missing conf reference to root node of experience fragments
CQ-4319841
=> Add missing conf reference to XF

site/src/main/content/jcr_root/content/aem-site-template-basic/.content.xml
- replace foundation/redirect component with cmp page
fixes #38
=> Fix resource type of root page

theme/package-lock.json, theme/package.json, theme/webpack.dev.js
Webpack watch replaces chokidar cli. Fixes #42 and #34
=> Webpack watch replaces chokidar cli

site/src/main/content/jcr_root/conf/aem-site-template-basic/settings/wcm/policies/.content.xml, site/src/main/content/jcr_root/conf/aem-site-template-basic/settings/wcm/templates/xf-web-variation/policies/.content.xml, site/src/main/content/jcr_root/content/experience-fragments/aem-site-template-basic/en/site/footer/master/.content.xml, site/src/main/content/jcr_root/content/experience-fragments/aem-site-template-basic/en/site/header/master/.content.xml, theme/src/components/experiencefragment/_experiencefragment_footer.scss, theme/src/components/experiencefragment/_experiencefragment_header.scss
=> Fix Experience Fragment Styling

package.json
- adds an open item configuration; to open the English home page on successful site creation.
=> SITES-3585 - [Sites30] Configure Standard Site Template open item

package-lock.json, package.json
=> Bump aem-site-template-builder to 2.3.1

site/src/main/content/jcr_root/conf/aem-site-template-standard/settings/wcm/policies/.content.xml
=> Core Components should be referenced by resource type in the policies of standard site template

theme/README.md
=> Updated theme deployment instructions

site/src/main/content/jcr_root/conf/aem-site-template-standard/settings/wcm/policies/.content.xml, theme/src/components/embed/_embed.scss
=> SITES-10562 - Embed Youtube component not honoring Aspect ratio

theme/package.json
Updating to parcel 2.7.0 to fix issues with SASS files not being updated in dist due to parcel cache management issues.
[SASS updates not reflected in dist files due to Parcel cache](https://github.com/adobe/aem-site-template-standard/issues/94)
=> Fix for dist files not picking up SASS file updates due to Parcel cache

theme/package-lock.json, theme/src/theme.scss
=> SITES-29275: use rel. references in scss to work with parcel sass 2.7+
